version: 2

# Build configuration
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python:
    version: 3.12

# Requirements file
requirements_file: docs/requirements.txt

# Documentation versions
documentation_versions:
  latest: main

